"""Validate small-batch MERT extraction and sample-keyed DEAM alignment.

This Stage B2 runner processes exactly eight fixed real DEAM excerpts in two
dynamic batches of four. It compares each masked-pooled batch representation
with an independently extracted single-item representation and writes only a
small JSON validation record, never an embedding cache.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import pandas as pd
import torch


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPOSITORY_ROOT / "src"))

from mert_emotion_probing.audio import (  # noqa: E402
    convert_to_mono,
    load_audio,
    resample_mono,
)
from mert_emotion_probing.mert import (  # noqa: E402
    extract_hidden_states,
    feature_frame_mask,
    load_frozen_mert,
    masked_temporal_mean_pool,
    prepare_mert_batch,
    prepare_mert_inputs,
    temporal_mean_pool,
)


TARGET_SAMPLE_RATE = 24_000
BATCH_SIZE = 4
ALLCLOSE_RTOL = 1e-4
ALLCLOSE_ATOL = 1e-5

# Order is deliberate: the first batch spans the observed excerpt-duration
# extremes, while the second covers mono and unusual source-rate branches.
SELECTED_SAMPLES = {
    272: "shortest verified primary excerpt; 44.1 kHz stereo",
    1708: (
        "largest container-level duration in the Module A inventory; "
        "44.1 kHz mono; actual decoded length retained"
    ),
    10: "ordinary 44.1 kHz stereo reference used in earlier sanity checks",
    1198: "48 kHz stereo and documented container/decoded-duration discrepancy",
    811: "44.1 kHz mono reference used in earlier sanity checks",
    1024: "only verified 16 kHz primary excerpt; stereo",
    1640: "22.05 kHz stereo resampling branch",
    1303: "48 kHz stereo with approximately 45-second decoded duration",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--audio-root", type=Path, default=Path("data/raw/deam/audio")
    )
    parser.add_argument(
        "--mapping-csv",
        type=Path,
        default=Path("data/raw/deam/verification/deam_item_mapping.csv"),
    )
    parser.add_argument(
        "--split-csv",
        type=Path,
        default=None,
        help="Existing locked split table; never generated by this script.",
    )
    parser.add_argument(
        "--model-source",
        default="m-a-p/MERT-v1-95M",
        help="Canonical model ID or a local snapshot of that same checkpoint.",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=Path(
            "data/raw/deam/verification/"
            "module_b_stage2_batched_alignment_validation.json"
        ),
    )
    return parser.parse_args()


def find_audio(audio_root: Path, song_id: int) -> Path:
    matches = list(audio_root.rglob(f"{song_id}.mp3"))
    if len(matches) != 1:
        raise FileNotFoundError(
            f"Expected one MP3 for ID {song_id}, found {len(matches)}"
        )
    return matches[0]


def load_mapping(path: Path) -> pd.DataFrame:
    mapping = pd.read_csv(path)
    required = {
        "song_id",
        "valence_mean",
        "arousal_mean",
        "is_full_song",
        "year_or_subset",
    }
    missing = required - set(mapping.columns)
    if missing:
        raise ValueError(f"Mapping table is missing columns: {sorted(missing)}")
    if mapping["song_id"].duplicated().any():
        duplicates = mapping.loc[
            mapping["song_id"].duplicated(keep=False), "song_id"
        ].tolist()
        raise ValueError(f"Mapping table has duplicate song IDs: {duplicates}")
    return mapping.set_index("song_id", verify_integrity=True)


def load_existing_split(path: Path | None) -> tuple[dict[int, str], dict[str, Any]]:
    if path is None:
        return {}, {
            "available": False,
            "source": None,
            "reason": (
                "No split source was supplied because repository inspection found "
                "no Module A train/validation/test split artifact or definition."
            ),
            "new_split_created": False,
        }
    if not path.is_file():
        raise FileNotFoundError(f"Split source does not exist: {path}")

    table = pd.read_csv(path)
    id_column = "song_id" if "song_id" in table else "sample_id"
    required = {id_column, "split"}
    missing = required - set(table.columns)
    if missing:
        raise ValueError(f"Split table is missing columns: {sorted(missing)}")
    if table[id_column].duplicated().any():
        raise ValueError("Split table contains duplicate sample IDs")
    split_lookup = {
        int(row[id_column]): str(row["split"])
        for _, row in table[[id_column, "split"]].iterrows()
    }
    return split_lookup, {
        "available": True,
        "source": str(path),
        "reason": None,
        "new_split_created": False,
    }


def tensor_checks(tensor: torch.Tensor) -> dict[str, Any]:
    return {
        "dtype": str(tensor.dtype),
        "device": str(tensor.device),
        "finite": bool(torch.isfinite(tensor).all().item()),
        "contains_nan": bool(torch.isnan(tensor).any().item()),
        "contains_inf": bool(torch.isinf(tensor).any().item()),
        "all_zero": bool(torch.count_nonzero(tensor).item() == 0),
        "requires_grad": bool(tensor.requires_grad),
    }


def main() -> None:
    args = parse_args()
    selected_ids = list(SELECTED_SAMPLES)
    if len(selected_ids) != 8 or len(set(selected_ids)) != 8:
        raise RuntimeError("Stage B2 requires exactly eight unique fixed sample IDs")

    torch.manual_seed(0)
    torch.cuda.manual_seed_all(0)
    device = torch.device("cuda")

    mapping = load_mapping(args.mapping_csv)
    missing_mapping_ids = [song_id for song_id in selected_ids if song_id not in mapping.index]
    if missing_mapping_ids:
        raise KeyError(f"Selected IDs missing from mapping table: {missing_mapping_ids}")
    split_lookup, split_source = load_existing_split(args.split_csv)

    feature_extractor, model = load_frozen_mert(
        model_id=args.model_source, device=device
    )
    model_state = {
        "model_id": "m-a-p/MERT-v1-95M",
        "loaded_from": str(args.model_source),
        "evaluation_mode": not model.training,
        "all_parameters_frozen": all(
            not parameter.requires_grad for parameter in model.parameters()
        ),
        "dtype": str(next(model.parameters()).dtype),
        "device": str(next(model.parameters()).device),
        "feature_extractor_do_normalize": bool(feature_extractor.do_normalize),
        "feature_extractor_normalization": str(model.config.feat_extract_norm),
        "transformers_version": __import__("transformers").__version__,
        "torch_version": torch.__version__,
        "gpu": torch.cuda.get_device_name(0),
    }

    waveforms: dict[int, torch.Tensor] = {}
    sample_records: dict[int, dict[str, Any]] = {}
    for song_id in selected_ids:
        audio_path = find_audio(args.audio_root, song_id)
        loaded = load_audio(audio_path)
        mono = convert_to_mono(loaded.waveform)
        resampled = resample_mono(
            mono, loaded.sample_rate, target_rate=TARGET_SAMPLE_RATE
        )
        metadata = mapping.loc[song_id]
        if bool(metadata["is_full_song"]):
            raise ValueError(f"Selected ID {song_id} is not in the primary excerpt set")
        waveforms[song_id] = resampled
        sample_records[song_id] = {
            "sample_id": song_id,
            "selection_reason": SELECTED_SAMPLES[song_id],
            "audio_path": audio_path.as_posix(),
            "metadata_subset": str(metadata["year_or_subset"]),
            "source_waveform_shape": list(loaded.waveform.shape),
            "source_sample_rate": loaded.sample_rate,
            "source_channels": loaded.channels,
            "decoded_duration_seconds": loaded.duration_seconds,
            "mono_length": int(mono.numel()),
            "resampled_length": int(resampled.numel()),
            "valence": float(metadata["valence_mean"]),
            "arousal": float(metadata["arousal_mean"]),
            "split": split_lookup.get(song_id),
        }

    single_representations: dict[int, torch.Tensor] = {}
    single_checks: dict[int, dict[str, Any]] = {}
    for song_id in selected_ids:
        model_inputs = prepare_mert_inputs(
            waveforms[song_id],
            feature_extractor,
            sample_rate=TARGET_SAMPLE_RATE,
            device=device,
        )
        hidden_states = extract_hidden_states(model, model_inputs)
        pooled = temporal_mean_pool(hidden_states)[0]
        single_representations[song_id] = pooled.detach().cpu()
        single_checks[song_id] = {
            "model_input_shape": list(model_inputs["input_values"].shape),
            "input_attention_mask_shape": list(model_inputs["attention_mask"].shape),
            "valid_input_positions": int(model_inputs["attention_mask"].sum().item()),
            "hidden_state_shape": list(hidden_states[0].shape),
            "item_representation_shape": list(pooled.shape),
            **tensor_checks(pooled),
        }
        del model_inputs, hidden_states, pooled
        torch.cuda.empty_cache()

    batched_representations: dict[int, torch.Tensor] = {}
    batch_records: list[dict[str, Any]] = []
    for batch_index, start in enumerate(range(0, len(selected_ids), BATCH_SIZE)):
        batch_ids = selected_ids[start : start + BATCH_SIZE]
        model_inputs = prepare_mert_batch(
            [waveforms[song_id] for song_id in batch_ids],
            feature_extractor,
            sample_rate=TARGET_SAMPLE_RATE,
            device=device,
        )
        attention_mask = model_inputs["attention_mask"]
        hidden_states = extract_hidden_states(model, model_inputs)
        frame_mask = feature_frame_mask(
            model, attention_mask, hidden_states[0].shape[1]
        )
        pooled = masked_temporal_mean_pool(hidden_states, frame_mask)

        valid_input_counts = attention_mask.sum(dim=1).tolist()
        valid_frame_counts = frame_mask.sum(dim=1).tolist()
        for row_index, song_id in enumerate(batch_ids):
            batched_representations[song_id] = pooled[row_index].detach().cpu()

        batch_records.append(
            {
                "batch_index": batch_index,
                "sample_ids_in_batch_row_order": batch_ids,
                "original_resampled_lengths": [
                    int(waveforms[song_id].numel()) for song_id in batch_ids
                ],
                "padded_input_shape": list(model_inputs["input_values"].shape),
                "input_attention_mask_shape": list(attention_mask.shape),
                "valid_input_positions": [int(value) for value in valid_input_counts],
                "hidden_state_count": len(hidden_states),
                "each_hidden_state_shape": list(hidden_states[0].shape),
                "feature_frame_mask_shape": list(frame_mask.shape),
                "valid_feature_frames": [int(value) for value in valid_frame_counts],
                "pooled_batch_shape": list(pooled.shape),
                "pooled_checks": tensor_checks(pooled),
            }
        )
        del model_inputs, attention_mask, hidden_states, frame_mask, pooled
        torch.cuda.empty_cache()

    comparisons: list[dict[str, Any]] = []
    for song_id in selected_ids:
        single = single_representations[song_id]
        batched = batched_representations[song_id]
        difference = (single - batched).abs()
        comparisons.append(
            {
                "sample_id": song_id,
                "single_shape": list(single.shape),
                "batched_shape": list(batched.shape),
                "max_absolute_difference": float(difference.max().item()),
                "mean_absolute_difference": float(difference.mean().item()),
                "allclose": bool(
                    torch.allclose(
                        single,
                        batched,
                        rtol=ALLCLOSE_RTOL,
                        atol=ALLCLOSE_ATOL,
                    )
                ),
            }
        )

    representation_ids = set(batched_representations)
    alignment_rows = []
    for song_id in selected_ids:
        record = sample_records[song_id]
        alignment_rows.append(
            {
                "sample_id": song_id,
                "representation_shape": list(
                    batched_representations[song_id].shape
                ),
                "valence": record["valence"],
                "arousal": record["arousal"],
                "split": record["split"],
            }
        )

    alignment_checks = {
        "sample_id_is_authoritative_key": True,
        "selected_id_count": len(selected_ids),
        "duplicate_selected_ids": len(selected_ids) != len(set(selected_ids)),
        "missing_representations": sorted(set(selected_ids) - representation_ids),
        "unexpected_representation_ids": sorted(representation_ids - set(selected_ids)),
        "missing_valence_ids": [
            row["sample_id"] for row in alignment_rows if pd.isna(row["valence"])
        ],
        "missing_arousal_ids": [
            row["sample_id"] for row in alignment_rows if pd.isna(row["arousal"])
        ],
        "missing_split_ids": [
            row["sample_id"] for row in alignment_rows if row["split"] is None
        ],
        "unexpected_id_mismatch": False,
    }
    id_label_representation_alignment_passed = not any(
        [
            alignment_checks["duplicate_selected_ids"],
            alignment_checks["missing_representations"],
            alignment_checks["unexpected_representation_ids"],
            alignment_checks["missing_valence_ids"],
            alignment_checks["missing_arousal_ids"],
            alignment_checks["unexpected_id_mismatch"],
        ]
    )
    split_alignment_passed = not alignment_checks["missing_split_ids"]
    single_vs_batch_passed = all(row["allclose"] for row in comparisons)
    numerical_checks_passed = all(
        single_checks[song_id]["finite"]
        and not single_checks[song_id]["all_zero"]
        and not single_checks[song_id]["requires_grad"]
        for song_id in selected_ids
    ) and all(
        record["pooled_checks"]["finite"]
        and not record["pooled_checks"]["all_zero"]
        and not record["pooled_checks"]["requires_grad"]
        for record in batch_records
    )

    stage_passed = all(
        [
            model_state["evaluation_mode"],
            model_state["all_parameters_frozen"],
            single_vs_batch_passed,
            numerical_checks_passed,
            id_label_representation_alignment_passed,
            split_alignment_passed,
        ]
    )
    output = {
        "stage": "Module B Stage 2 — Batched Representation & Alignment Validation",
        "stage_passed": stage_passed,
        "status": "passed" if stage_passed else "blocked_or_failed",
        "fixed_tolerance_declared_before_comparison": {
            "rtol": ALLCLOSE_RTOL,
            "atol": ALLCLOSE_ATOL,
        },
        "model": model_state,
        "split_source": split_source,
        "selected_sample_ids": selected_ids,
        "sample_records": [sample_records[song_id] for song_id in selected_ids],
        "single_item_extraction": [
            {"sample_id": song_id, **single_checks[song_id]}
            for song_id in selected_ids
        ],
        "batched_extraction": batch_records,
        "single_vs_batched_comparisons": comparisons,
        "single_vs_batch_passed": single_vs_batch_passed,
        "alignment_rows": alignment_rows,
        "alignment_checks": alignment_checks,
        "id_label_representation_alignment_passed": (
            id_label_representation_alignment_passed
        ),
        "split_alignment_passed": split_alignment_passed,
        "numerical_checks_passed": numerical_checks_passed,
        "embeddings_saved": False,
    }
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(
        json.dumps(output, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(json.dumps(output, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
